nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173'] # Remplacez par l'URL de votre frontend Vue.js
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': # Autoriser les requêtes vers vos routes d'API
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
